-- ══════════════════════════════════════════════════════════════════════
-- 一人CEO — 完整数据库 Schema (Supabase PostgreSQL)
-- 版本: v1.0.13 | 更新日期: 2026-03-15
--
-- 仅用于全新 Supabase 项目的首次初始化。
-- 使用 CREATE TABLE IF NOT EXISTS，对已存在的表为 no-op，不会清库。
-- 使用方法: 在 Supabase SQL Editor 中执行。
-- ══════════════════════════════════════════════════════════════════════


-- ┌─────────────────────────────────────────────────────────────────────┐
-- │  1. TABLES — 12 张表                                               │
-- └─────────────────────────────────────────────────────────────────────┘

-- ── 线索 (销售漏斗中的潜在客户) ──
CREATE TABLE IF NOT EXISTS leads (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  industry   TEXT DEFAULT '',
  needs      TEXT DEFAULT '',
  website    TEXT DEFAULT '',
  "column"   TEXT DEFAULT 'new',
  "aiDraft"  TEXT DEFAULT '',
  source     TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  soft_deleted BOOLEAN DEFAULT FALSE
);

-- 复合索引: 覆盖主要查询 WHERE user_id = ? AND soft_deleted = false
CREATE INDEX IF NOT EXISTS idx_leads_user_active ON leads (user_id, soft_deleted, "column");
CREATE INDEX IF NOT EXISTS idx_leads_created ON leads (created_at);

-- ── 客户 ──
CREATE TABLE IF NOT EXISTS clients (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                 UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name                    TEXT NOT NULL,
  industry                TEXT DEFAULT '',
  plan_tier               TEXT DEFAULT '',
  status                  TEXT DEFAULT 'Active',
  brand_context           TEXT DEFAULT '',
  mrr                     DOUBLE PRECISION DEFAULT 0,
  joined_at               TIMESTAMPTZ DEFAULT now(),
  subscription_start_date TEXT DEFAULT '',
  paused_at               TEXT DEFAULT '',
  resumed_at              TEXT DEFAULT '',
  cancelled_at            TEXT DEFAULT '',
  mrr_effective_from      TEXT DEFAULT '',
  company_name            TEXT DEFAULT '',
  contact_name            TEXT DEFAULT '',
  contact_email           TEXT DEFAULT '',
  contact_phone           TEXT DEFAULT '',
  billing_type            TEXT DEFAULT 'subscription',
  project_fee             DOUBLE PRECISION DEFAULT 0,
  project_end_date        TEXT DEFAULT '',
  tax_mode                TEXT DEFAULT 'none',
  tax_rate                DOUBLE PRECISION DEFAULT 0,
  drive_folder_url        TEXT DEFAULT '',
  payment_method          TEXT DEFAULT 'auto',
  created_at              TIMESTAMPTZ DEFAULT now(),
  updated_at              TIMESTAMPTZ DEFAULT now(),
  soft_deleted            BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_clients_user_active ON clients (user_id, soft_deleted, status);

-- ── 任务 ──
CREATE TABLE IF NOT EXISTS tasks (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title            TEXT NOT NULL,
  client           TEXT DEFAULT '',
  priority         TEXT DEFAULT 'Medium',
  due              TEXT DEFAULT '',
  "column"         TEXT DEFAULT 'todo',
  "originalRequest" TEXT DEFAULT '',
  "aiBreakdown"    TEXT DEFAULT '',
  "aiMjPrompts"    TEXT DEFAULT '',
  "aiStory"        TEXT DEFAULT '',
  created_at       TIMESTAMPTZ DEFAULT now(),
  updated_at       TIMESTAMPTZ DEFAULT now(),
  soft_deleted     BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_tasks_user_active ON tasks (user_id, soft_deleted, "column");

-- ── 定价方案 ──
CREATE TABLE IF NOT EXISTS plans (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name           TEXT NOT NULL,
  price          DOUBLE PRECISION DEFAULT 0,
  "deliverySpeed" TEXT DEFAULT '',
  features       TEXT DEFAULT '[]',
  clients        INTEGER DEFAULT 0,
  created_at     TIMESTAMPTZ DEFAULT now(),
  updated_at     TIMESTAMPTZ DEFAULT now(),
  soft_deleted   BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_plans_user ON plans (user_id, soft_deleted);

-- ── 财务流水 ──
CREATE TABLE IF NOT EXISTS finance_transactions (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type        TEXT DEFAULT 'income',
  amount      DOUBLE PRECISION DEFAULT 0,
  category    TEXT DEFAULT '',
  description TEXT DEFAULT '',
  date        TEXT DEFAULT '',
  status      TEXT DEFAULT '已完成',
  tax_mode    TEXT DEFAULT 'none',
  tax_rate    DOUBLE PRECISION DEFAULT 0,
  tax_amount  DOUBLE PRECISION DEFAULT 0,
  client_id   BIGINT,
  client_name TEXT DEFAULT '',
  source      TEXT DEFAULT 'manual',
  source_id   BIGINT,
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_at  TIMESTAMPTZ DEFAULT now(),
  soft_deleted BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_finance_user_active ON finance_transactions (user_id, soft_deleted);
CREATE INDEX IF NOT EXISTS idx_finance_date ON finance_transactions (date);
CREATE INDEX IF NOT EXISTS idx_finance_status ON finance_transactions (status);
CREATE INDEX IF NOT EXISTS idx_finance_source ON finance_transactions (user_id, source, source_id, date) WHERE soft_deleted = FALSE;

-- ── 付款里程碑 ──
CREATE TABLE IF NOT EXISTS payment_milestones (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  client_id       BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  label           TEXT NOT NULL DEFAULT '',
  amount          DOUBLE PRECISION NOT NULL DEFAULT 0,
  percentage      DOUBLE PRECISION DEFAULT 0,
  due_date        TEXT DEFAULT '',
  paid_date       TEXT DEFAULT '',
  payment_method  TEXT DEFAULT '',
  status          TEXT DEFAULT 'pending',
  invoice_number  TEXT DEFAULT '',
  note            TEXT DEFAULT '',
  finance_tx_id   BIGINT,
  sort_order      INTEGER DEFAULT 0,
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now(),
  soft_deleted    BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_pm_user_active ON payment_milestones (user_id, soft_deleted, status);
CREATE INDEX IF NOT EXISTS idx_pm_client ON payment_milestones (client_id);
CREATE INDEX IF NOT EXISTS idx_pm_due ON payment_milestones (due_date);

-- ── 内容草稿 ──
CREATE TABLE IF NOT EXISTS content_drafts (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  topic      TEXT DEFAULT '',
  platform   TEXT DEFAULT '',
  language   TEXT DEFAULT 'zh',
  content    TEXT DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now(),
  soft_deleted BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_content_user ON content_drafts (user_id, soft_deleted);

-- ── 活动日志 ──
CREATE TABLE IF NOT EXISTS activity_log (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL,
  entity_id   BIGINT,
  action      TEXT NOT NULL,
  title       TEXT NOT NULL,
  detail      TEXT DEFAULT '',
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_activity_user_created ON activity_log (user_id, created_at DESC);

-- ── 订阅台账 ──
CREATE TABLE IF NOT EXISTS client_subscription_ledger (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  client_id    BIGINT NOT NULL,
  client_name  TEXT NOT NULL,
  plan_tier    TEXT DEFAULT '',
  amount       DOUBLE PRECISION NOT NULL,
  ledger_month TEXT NOT NULL,
  created_at   TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, client_id, ledger_month)
);

CREATE INDEX IF NOT EXISTS idx_ledger_user ON client_subscription_ledger (user_id);

-- ── 今日聚焦状态 ──
CREATE TABLE IF NOT EXISTS today_focus_state (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  focus_date TEXT NOT NULL,
  focus_key  TEXT NOT NULL,
  status     TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, focus_date, focus_key)
);

CREATE INDEX IF NOT EXISTS idx_focus_state_user_date ON today_focus_state (user_id, focus_date);

-- ── 今日手动事件 ──
CREATE TABLE IF NOT EXISTS today_focus_manual (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  focus_date TEXT NOT NULL,
  type       TEXT NOT NULL DEFAULT '系统',
  title      TEXT NOT NULL,
  note       TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  soft_deleted BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_focus_manual_user_date ON today_focus_manual (user_id, focus_date, soft_deleted);

-- ── 应用设置 ──
CREATE TABLE IF NOT EXISTS app_settings (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  key     TEXT NOT NULL,
  value   TEXT DEFAULT '',
  PRIMARY KEY (user_id, key)
);


-- ┌─────────────────────────────────────────────────────────────────────┐
-- │  2. ROW LEVEL SECURITY                                             │
-- └─────────────────────────────────────────────────────────────────────┘

DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOR tbl IN
    SELECT unnest(ARRAY[
      'leads', 'clients', 'tasks', 'plans', 'finance_transactions',
      'content_drafts', 'activity_log', 'client_subscription_ledger',
      'today_focus_state', 'today_focus_manual', 'app_settings',
      'payment_milestones'
    ])
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', tbl);
    EXECUTE format(
      'CREATE POLICY "users_own_data_%1$s" ON %1$I FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id)',
      tbl
    );
  END LOOP;
END $$;


-- ┌─────────────────────────────────────────────────────────────────────┐
-- │  3. AUTO-UPDATE updated_at 触发器                                   │
-- └─────────────────────────────────────────────────────────────────────┘

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOR tbl IN
    SELECT unnest(ARRAY[
      'leads', 'clients', 'tasks', 'plans', 'finance_transactions',
      'content_drafts', 'today_focus_state', 'today_focus_manual',
      'payment_milestones'
    ])
  LOOP
    EXECUTE format(
      'CREATE TRIGGER trg_updated_at_%1$s BEFORE UPDATE ON %1$I FOR EACH ROW EXECUTE FUNCTION update_updated_at()',
      tbl
    );
  END LOOP;
END $$;


-- ┌─────────────────────────────────────────────────────────────────────┐
-- │  4. REALTIME                                                       │
-- └─────────────────────────────────────────────────────────────────────┘

DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOR tbl IN
    SELECT unnest(ARRAY[
      'leads', 'clients', 'tasks', 'plans', 'finance_transactions',
      'content_drafts', 'today_focus_state', 'today_focus_manual',
      'payment_milestones'
    ])
  LOOP
    BEGIN
      EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE %I', tbl);
    EXCEPTION WHEN duplicate_object THEN
      NULL;
    END;
  END LOOP;
END $$;
