-- ══════════════════════════════════════════════════════════════════════
-- Payment Milestones for project-based clients
-- Tracks deposits, midway payments, final payments, etc.
-- ══════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS payment_milestones (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  client_id       BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  label           TEXT NOT NULL DEFAULT '',
  amount          DOUBLE PRECISION NOT NULL DEFAULT 0,
  percentage      DOUBLE PRECISION DEFAULT 0,
  due_date        TEXT DEFAULT '',
  paid_date       TEXT DEFAULT '',
  payment_method  TEXT DEFAULT '',
  status          TEXT DEFAULT 'pending',
  invoice_number  TEXT DEFAULT '',
  note            TEXT DEFAULT '',
  finance_tx_id   BIGINT,
  sort_order      INTEGER DEFAULT 0,
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now(),
  soft_deleted    BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_pm_user   ON payment_milestones (user_id);
CREATE INDEX IF NOT EXISTS idx_pm_client ON payment_milestones (client_id);
CREATE INDEX IF NOT EXISTS idx_pm_status ON payment_milestones (status);
CREATE INDEX IF NOT EXISTS idx_pm_due    ON payment_milestones (due_date);

-- RLS
ALTER TABLE payment_milestones ENABLE ROW LEVEL SECURITY;
CREATE POLICY "users_own_data_payment_milestones" ON payment_milestones
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Auto-update updated_at
CREATE TRIGGER trg_updated_at_payment_milestones
  BEFORE UPDATE ON payment_milestones
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE payment_milestones;
