-- ══════════════════════════════════════════════════════════════════════
-- Migration 003: Multi-project per client
-- Allows project-type clients to have multiple projects over time.
-- Each project has its own fee, dates, milestones, and finance records.
-- ══════════════════════════════════════════════════════════════════════

-- ┌─────────────────────────────────────────────────────────────────────┐
-- │  1. CREATE client_projects TABLE                                   │
-- └─────────────────────────────────────────────────────────────────────┘

CREATE TABLE IF NOT EXISTS client_projects (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id            UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  client_id          BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  name               TEXT NOT NULL DEFAULT '',
  project_fee        DOUBLE PRECISION DEFAULT 0,
  project_start_date TEXT DEFAULT '',
  project_end_date   TEXT DEFAULT '',
  status             TEXT DEFAULT 'active',  -- active | completed | cancelled
  tax_mode           TEXT DEFAULT 'none',
  tax_rate           DOUBLE PRECISION DEFAULT 0,
  note               TEXT DEFAULT '',
  sort_order         INTEGER DEFAULT 0,
  created_at         TIMESTAMPTZ DEFAULT now(),
  updated_at         TIMESTAMPTZ DEFAULT now(),
  soft_deleted       BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_cp_client ON client_projects (client_id, soft_deleted);
CREATE INDEX IF NOT EXISTS idx_cp_user   ON client_projects (user_id, soft_deleted);

-- ┌─────────────────────────────────────────────────────────────────────┐
-- │  2. ADD project_id TO EXISTING TABLES                              │
-- └─────────────────────────────────────────────────────────────────────┘

ALTER TABLE payment_milestones ADD COLUMN IF NOT EXISTS project_id BIGINT;
ALTER TABLE finance_transactions ADD COLUMN IF NOT EXISTS project_id BIGINT;

-- ┌─────────────────────────────────────────────────────────────────────┐
-- │  3. RLS + TRIGGER + REALTIME                                       │
-- └─────────────────────────────────────────────────────────────────────┘

ALTER TABLE client_projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_own_data_client_projects" ON client_projects
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE TRIGGER trg_updated_at_client_projects
  BEFORE UPDATE ON client_projects
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

ALTER PUBLICATION supabase_realtime ADD TABLE client_projects;

-- ┌─────────────────────────────────────────────────────────────────────┐
-- │  4. AUTO-MIGRATE EXISTING PROJECT DATA                             │
-- └─────────────────────────────────────────────────────────────────────┘

-- For each project-type client, create a client_projects row from existing data
INSERT INTO client_projects (user_id, client_id, name, project_fee, project_start_date, project_end_date, status, tax_mode, tax_rate)
SELECT
  user_id,
  id,
  COALESCE(NULLIF(company_name, ''), NULLIF(name, ''), 'Project 1'),
  COALESCE(project_fee, 0),
  COALESCE(subscription_start_date, ''),
  COALESCE(project_end_date, ''),
  CASE WHEN status = 'Active' THEN 'active'
       WHEN status = 'Completed' THEN 'completed'
       WHEN status = 'Cancelled' THEN 'cancelled'
       ELSE 'active' END,
  COALESCE(tax_mode, 'none'),
  COALESCE(tax_rate, 0)
FROM clients
WHERE billing_type = 'project' AND soft_deleted = FALSE
-- Only migrate if not already migrated
AND id NOT IN (SELECT client_id FROM client_projects);

-- Backfill project_id on milestones
UPDATE payment_milestones pm
SET project_id = (
  SELECT cp.id FROM client_projects cp
  WHERE cp.client_id = pm.client_id AND cp.soft_deleted = FALSE
  ORDER BY cp.created_at ASC LIMIT 1
)
WHERE pm.project_id IS NULL
  AND EXISTS (SELECT 1 FROM client_projects cp WHERE cp.client_id = pm.client_id);

-- Backfill project_id on finance transactions
UPDATE finance_transactions ft
SET project_id = (
  SELECT cp.id FROM client_projects cp
  WHERE cp.client_id = ft.client_id AND cp.soft_deleted = FALSE
  ORDER BY cp.created_at ASC LIMIT 1
)
WHERE ft.project_id IS NULL
  AND ft.source IN ('milestone', 'project_fee')
  AND EXISTS (SELECT 1 FROM client_projects cp WHERE cp.client_id = ft.client_id);
