
CREATE TABLE IF NOT EXISTS ai_agents (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name            TEXT NOT NULL DEFAULT '',
  avatar          TEXT DEFAULT '',
  role            TEXT DEFAULT '',
  personality     TEXT DEFAULT '',
  rules           TEXT DEFAULT '',
  tools           TEXT DEFAULT '[]',
  conversation_starters TEXT DEFAULT '[]',
  template_id     TEXT DEFAULT '',
  is_default      BOOLEAN DEFAULT FALSE,
  sort_order      INTEGER DEFAULT 0,
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now(),
  soft_deleted    BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_agents_user_active
  ON ai_agents (user_id, soft_deleted);

ALTER TABLE ai_agents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "select_own_ai_agents" ON ai_agents
  FOR SELECT USING (auth.uid() = user_id AND soft_deleted = false);

CREATE POLICY "insert_own_ai_agents" ON ai_agents
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "update_own_ai_agents" ON ai_agents
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "delete_own_ai_agents" ON ai_agents
  FOR DELETE USING (auth.uid() = user_id);

CREATE TRIGGER trg_updated_at_ai_agents
  BEFORE UPDATE ON ai_agents
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

ALTER PUBLICATION supabase_realtime ADD TABLE ai_agents;
;
